@startuml
class Libro {
    + Libro()
    + Libro(id:int, titulo:string, tipoLibro:string, autor:string, precioTotal:decimal, stock:int, calificacionMedia:decimal, fechaLanzamiento:DateTime)
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + Autor : string <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + PrecioReposicion : decimal <<get>> <<set>>
    + Stock : int <<get>> <<set>>
    + Editorial : Editorial <<get>> <<set>>
    + Genero : Genero <<get>> <<set>>
    + CompraItems : IList<CompraItem> <<get>> <<set>>
    + ReposicionItems : IList<ReposicionItem> <<get>> <<set>>
    + TipoLibro : string <<get>> <<set>>
    + CalificacionMedia : decimal <<get>> <<set>>
}
class "IList`1"<T> {
}
Libro --> "Editorial" Editorial
Libro --> "Genero" Genero
Libro --> "CompraItems<CompraItem>" "IList`1"
Libro --> "FechaLanzamiento" DateTime
Libro o-> "ResenaItems<ResenaItem>" "IList`1"
@enduml
