@startuml
class ReposicionItem {
    + ReposicionItem()
    + ReposicionItem(libroId:string, reposicionId:string, cantidadReposicion:int, libro:Libro, reposicion:Reposicion)
    + CantidadReposicion : int <<get>> <<set>>
    + LibroId : string <<get>> <<set>>
    + ReposicionId : string <<get>> <<set>>
    + Libro : Libro <<get>> <<set>>
    + Reposicion : Reposicion <<get>> <<set>>
}
}
ReposicionItem --> "Libro" Libro
ReposicionItem --> "Reposicion" Reposicion
@enduml
