@startuml
class Reposicion {
    + Reposicion()
    + Reposicion(id:string, fechaReposicion:DateTime, precioTotal:double, comentario:string, reposicionItems:IList<ReposicionItem>)
    + Id : string <<get>> <<set>>
    + FechaReposicion : DateTime <<get>> <<set>>
    + PrecioTotal : double <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
    + ReposicionItems : IList<ReposicionItem> <<get>> <<set>>
}
Reposicion "1" o-- "0..*" ReposicionItem : ReposicionItems
ApplicationUser "1" -- "0..*" Reposicion : Reposiciones
MetodoPago "1" -- "1.*" Reposicion : MetodoPagos
@enduml
