@startuml
class Reposicion {
    + Reposicion()
    + Reposicion(id:string, fechaReposicion:DateTime, precioTotal:double, comentario:string, reposicionItems:IList<ReposicionItem>)
    + Id : string <<get>> <<set>>
    + FechaReposicion : DateTime <<get>> <<set>>
    + PrecioTotal : double <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
    + ReposicionItems : IList<ReposicionItem> <<get>> <<set>>
}
@enduml
