@startuml

class Resena {
    + Resena()
    + Resena(id:int, fechaResena:DateTime, titulo:string)
    + Id : int <<get>> <<set>>
    + FechaResena : DateTime <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
}

Resena "1" o-- "0..*" ResenaItem : ResenaItems
ApplicationUser "1" -- "0..*" Resena : Resenas

@enduml