@startuml
class Subasta {
    + Subasta(id:String, precioSubasta:double, fechaSubasta:DateTime)
    + PrecioSubasta : double <<get>> <<set>>
}
Subasta --> "Id" String
Subasta --> "FechaSubasta" DateTime
@enduml
